export enum ErrorCode {
  // Auth
  AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED = "AUTH_UNAUTHORIZED",

  // Teacher
  TEACHER_MISSING_FIELDS = "TEACHER_MISSING_FIELDS",
  TEACHER_EMAIL_CONFLICT = "TEACHER_EMAIL_CONFLICT",
  TEACHER_NOT_FOUND = "TEACHER_NOT_FOUND",
  TEACHER_FORBIDDEN = "TEACHER_FORBIDDEN",

  // Options
  OPTION_MISSING_FIELDS = "OPTION_MISSING_FIELDS",
  OPTION_NOT_FOUND = "OPTION_NOT_FOUND",
  OPTIONS_NOT_FOUND = "OPTIONS_NOT_FOUND",

  // Experiment
  EXPERIMENT_MISSING_FIELDS = "EXPERIMENT_MISSING_FIELDS",
  EXPERIMENT_PIN_CONFLICT = "EXPERIMENT_PIN_CONFLICT",
  EXPERIMENT_NOT_FOUND = "EXPERIMENT_NOT_FOUND",

  // Response
  RESPONSE_PIN_REQUIRED = "RESPONSE_PIN_REQUIRED",

  // Generic
  BAD_REQUEST = "BAD_REQUEST",
  CONFLICT = "CONFLICT",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL = "INTERNAL",
}

export default ErrorCode;
